remove need to use ssh agents

diff --git a/yamls/gtcustomers/serma.yaml b/yamls/gtcustomers/serma.yaml
--- a/yamls/gtcustomers/serma.yaml
+++ b/yamls/gtcustomers/serma.yaml
@@ -8,7 +8,12 @@ jobs:
     steps:
       - name: SSH Auth
         run: |
+          set -x
           PUBLIC_KEY=$(ssh -o StrictHostKeyChecking=no ${{ inputs.pwrl_host.resource.ip }}) cat ~/.ssh/id_rsa.pub)
+          if [ -z "$MY_VAR" ]; then
+            echo "ERROR: Unable to obtain public key"
+            exit 1
+          fi
           sed -i "s|__PUBLIC_KEY__|${PUBLIC_KEY}|g" utils/add_ssh_key.sh 
           sed -i "s|__PUBLIC_KEY__|${PUBLIC_KEY}|g" utils/remove_ssh_key.sh 
           ssh -o StrictHostKeyChecking=no ${{ inputs.gt_license_user }}@${{ inputs.gt_license_ip }} < utils/add_ssh_key.sh
